name: uw_risk_analytics
version: "1.0.0"
config-version: 2
profile: uw_risk_analytics

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  uw_risk_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  uw_risk_analytics:
    pincode_hazard:
      +column_types:
        pincode: varchar
        district: varchar
        state: varchar
        district_lgd: integer
        seismic_zone: varchar
        seismic_zone_max: varchar
        flood_area_pct: double
        cyclone_grade: varchar
        cyclone_note: varchar
